### ISSUE TITLE
1.0 release checklist

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#198]
For Cohttp 1.0 we probably want to fix these issues:
- [ ] bad request handling #146
- [x] empty chunk handling #136 
- [ ] normalize path segments #150 
- [ ] API inconsistencies #200 

Add examples:
- [ ] multipart form request #181 
- [ ] example of http fetch for lwt thats functorised like github (so compiles to js_of_ocaml)
- [x] add examples to README #43 

A test harness to run it through some stress tests to check for fd leakage would be very nice: http://andreas.github.io/2014/09/18/how-to-test-async-ocaml-code/

**Comment by rgrinberg** [comment]
I've added #281 to the milestone since not being able to make AWS is a little embarrassing.

**Comment by yomimono** [comment]
I think this issue is not useful since cohttp 1.0.0 has been released.  If it's tracking pieces of work that are still planned or there is some other purpose served by keeping it around, please feel free to reopen this issue (possibly with a more descriptive title).
